version: "3.3"

services:
  db:
    
    # image: mongo:latest
    image: andresvidal/rpi3-mongodb3:latest
    container_name: "ampgodb_container"
    volumes:
      - mongovol:/root/data/db
    networks:
      - ampgo
    ports:
      - 27017:27017


  ampgo:
    image: ampgo:0.1.10
    build: .
    environment:
      - AMPGO_SETUP=1
      - AMPGO_OFFSET=10
      - AMP_AMPDB_ADDR=mongodb://db:27017/ampgodb
      - AMPGO_TEMP_DIRPATH=/root/fsData/tmp
      - AMPGO_NUM_RAND_PICS=10
      - AMPGO_MONGODB_THUMB_ADDRESS=mongodb://db:27017/ampgothumb
      - AMPGO_MEDIA_PATH=/root/fsData
      - AMPGO_HARDRIVE_POSTERS_PATH=/root/fsData/Posters2
      - AMPGO_NO_ART_PIC_PATH=./static/images/animals.jpg
      - AMPGO_THUMB_PATH=/root/thumb
      - AMPGO_TEMPLATE_ADDRESS=./static/templates/AMPGO.template
      - AMPGO_SERVER_PORT=9090
      - AMPGO_SERVER_ADDRESS=http://192.168.0.61
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - ampgo
    ports:
      - 9090:9090
    volumes:
      - ampgovol:/root/fsData/
      - ampgopicvol:/root/thumb
      # -ampgostaticvol:/root/static/
    depends_on:
      - db

networks:
  ampgo:

volumes:
  ampgovol:
    driver: local
    driver_opts:
      type: none
      device: /media/pi/1EBA-071A/ssd3/
      # device: /media/pi/HD/Music
      # device: /home/pi/Music
      # device: /media/pi/FOO/Music
      # device: /media/pi/PiTB/media
      o: bind

  ampgopicvol:
    driver: local
    driver_opts:
      type: none
      device: /media/pi/1EBA-071A/Thumbnails/
      # device: /home/pi/Thumbnails
      # device: /home/pi/Thumbnails
      # device: /media/pi/HD/Thumbnails
      o: bind

  # ampgostaticvol:
    # driver: local
    # driver_opts:
      # type: none
      # device: /home/pi/Thumbnails
      # device: /home/pi/Thumbnails
      # device: /media/pi/HD/Thumbnails
      # o: bind


  mongovol:
    driver: local
    driver_opts:
      type: none
      device: /home/pi/data/db
      # device: /media/pi/HD/data/db
      o: bind

  # mgojsvol:
  #   driver: local
  #   driver_opts: 
  #     type: none
  #     device: /home/charlie/ampgo/init-mongo.js
  #     o: bind


